In [1]:
import torch
import torch.nn as nn

# Example sentence
tokens = ["I", "love", "cats"]

# Dummy vocab and token to index
vocab = {"I": 0, "love": 1, "cats": 2}
token_ids = torch.tensor([vocab[token] for token in tokens])  # [0, 1, 2]

# Parameters
vocab_size = len(vocab)
embedding_dim = 8  # small for demo
max_len = 10       # max sequence length

# Token embedding layer
token_embedding = nn.Embedding(vocab_size, embedding_dim)

# Positional embedding layer
positional_embedding = nn.Embedding(max_len, embedding_dim)

# Get token embeddings
token_embed = token_embedding(token_ids)  # shape: [seq_len, embedding_dim]

# Get position ids
position_ids = torch.arange(len(tokens))  # [0, 1, 2]
position_embed = positional_embedding(position_ids)

# Add token + positional embeddings
input_to_transformer = token_embed + position_embed

# Print shapes and values
print("Token Embeddings:\n", token_embed)
print("Positional Embeddings:\n", position_embed)
print("Final Input Embeddings:\n", input_to_transformer)


Token Embeddings:
 tensor([[ 1.2024,  0.4678, -1.5786,  0.3546,  2.8054, -0.2863, -0.3600,  0.0822],
        [-0.5053, -0.4286, -0.6893,  0.5698,  0.2327,  0.5770,  0.4346, -0.5526],
        [ 0.2038, -1.7253,  1.2436, -0.9613, -0.4870, -0.2419, -0.5929, -0.6119]],
       grad_fn=<EmbeddingBackward0>)
Positional Embeddings:
 tensor([[ 0.2047,  0.6722,  0.9930, -1.0348,  0.4537, -0.5721,  1.4479, -0.0806],
        [-1.7594,  0.2388,  1.1666,  0.0826,  0.6057, -1.8283, -0.1633,  0.6838],
        [ 0.4465,  0.0846, -0.7303, -0.0655, -0.3578,  0.8512,  1.2619, -1.2429]],
       grad_fn=<EmbeddingBackward0>)
Final Input Embeddings:
 tensor([[ 1.4071e+00,  1.1400e+00, -5.8560e-01, -6.8019e-01,  3.2591e+00,
         -8.5841e-01,  1.0878e+00,  1.5985e-03],
        [-2.2647e+00, -1.8981e-01,  4.7734e-01,  6.5249e-01,  8.3837e-01,
         -1.2513e+00,  2.7129e-01,  1.3118e-01],
        [ 6.5037e-01, -1.6407e+00,  5.1328e-01, -1.0268e+00, -8.4482e-01,
          6.0928e-01,  6.6899e-01, -1.8548e+

In [2]:
import torch
src = torch.rand(10, 32, 512)
src

tensor([[[8.4530e-01, 8.3958e-01, 6.3090e-01,  ..., 1.7678e-01,
          3.9026e-01, 9.3759e-02],
         [6.1257e-01, 8.2811e-01, 6.1914e-01,  ..., 6.3467e-01,
          6.6847e-02, 1.5522e-01],
         [9.4611e-01, 2.0432e-01, 1.0325e-01,  ..., 7.6874e-01,
          7.3100e-01, 6.1701e-01],
         ...,
         [3.0768e-01, 3.7561e-01, 3.2752e-01,  ..., 2.6194e-01,
          5.9659e-01, 3.2648e-01],
         [9.0996e-01, 4.4071e-01, 7.8828e-01,  ..., 7.3430e-01,
          5.2330e-01, 3.7182e-01],
         [3.8881e-01, 5.9088e-01, 8.3151e-01,  ..., 7.7734e-01,
          1.3464e-01, 6.1969e-01]],

        [[6.7009e-01, 3.5737e-02, 9.3212e-01,  ..., 4.6762e-01,
          2.7855e-01, 3.2459e-01],
         [9.4286e-01, 5.0366e-01, 8.7377e-01,  ..., 1.9735e-01,
          3.9417e-01, 2.2645e-01],
         [8.0502e-01, 2.0553e-01, 7.7426e-01,  ..., 8.2090e-01,
          9.6903e-02, 9.0193e-01],
         ...,
         [7.9726e-01, 4.7829e-01, 3.0107e-01,  ..., 7.3190e-01,
          4.672